# Generated by Django 3.0.6 on 2020-05-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200517_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=12)),
                ('message', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
